### ISSUE TITLE
Allow other modules to register scripts to the project

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/hugo-module-tnd-scripts#1]
Currently, only the project configuration can register scripts.

But other modules, like https://github.com/theNewDynamic/hugo-module-tnd-search should be able to do that, thus avoiding to have to sport their own script building logic.

As the project will always overwrite `site.Params.tnd_scripts` if set on a Module's `config.yaml`, we need another way.

I think the best approach is for each module to sports a unique, yet identifiable key under its own config:

```yaml
tnd_scripts_moduleID:
  scripts:
  - name: that_thing
     path: tnd_moduleID/js/that_thing.js
     params:
       greeting: bonjour
```

Then the script module can loook for any config key starting with `tnd_scripts_`  and append any scripts found underneath its `scripts` key.
