### ISSUE TITLE
Allow user to use partial to populate a script's `params`.

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/hugo-module-tnd-scripts#4]
For now script params (used through `import { params } from '@params'`). can only be declared through the yaml files. We want to let user use a returning partials to populate those:

```
tnd_scripts:
  scripts:
    - name: main
      path: /js/index.js
      params: partial func/GetMainScriptParams
```
